### ISSUE TITLE
Two features not working on AZERTY keyboards

### ISSUE THREAD

**Issue by steph643** [tekezo/Karabiner#327]
"Use PC Style Undo" and "Use PC Style Select All" do not work on my AZERTY keyboard.

As a workaround, I added the following in my private.xml:
```
    <autogen>
	  __KeyToKey__
	  KeyCode::W, ModifierFlag::CONTROL_L,
	  KeyCode::W, ModifierFlag::COMMAND_L      
    </autogen>
    <autogen>
	  __KeyToKey__
	  KeyCode::Q, ModifierFlag::CONTROL_L,
	  KeyCode::Q, ModifierFlag::COMMAND_L      
    </autogen>
```

**Comment by steph643** [comment]
Seen on https://groups.google.com/forum/#!msg/osx-karabiner/EZDLo1bFt60/4NkmhYGAk7MJ:

>These prepared settings are designed for QWERTY layout. 
>Please use new settings that will be added by this private.xml instead of prepared settings:
>https://github.com/tekezo/Files/blob/master/Karabiner/private.azerty_pc_style/private.xml

In case the link dies, here is the full suggested private.xml:
```
<?xml version="1.0"?>
<root>

  <item>
    <name>Use PC Style Undo for AZERTY</name>
    <appendix></appendix>
    <appendix>{{ PC_STYLE_BINDINGS_IGNORE_APPS_DESCRIPTION }}</appendix>
    <identifier>private.azerty_pc_style_undo</identifier>
    <not>{{ PC_STYLE_BINDINGS_IGNORE_APPS }}</not>
    {{ PC_STYLE_BINDINGS_IGNORE_EXTRA }}
    <autogen>__KeyToKey__ KeyCode::W, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::W, ModifierFlag::COMMAND_L</autogen>
  </item>

  <item>
    <name>Use PC Style Select All for AZERTY</name>
    <appendix></appendix>
    <appendix>{{ PC_STYLE_BINDINGS_IGNORE_APPS_DESCRIPTION }}</appendix>
    <identifier>private.azerty_pc_style_select_all</identifier>
    <not>{{ PC_STYLE_BINDINGS_IGNORE_APPS }}</not>
    {{ PC_STYLE_BINDINGS_IGNORE_EXTRA }}
    <autogen>__KeyToKey__ KeyCode::Q, MODIFIERFLAG_EITHER_LEFT_OR_RIGHT_CONTROL, KeyCode::Q, ModifierFlag::COMMAND_L</autogen>
  </item>

</root>
```

**Comment by tekezo** [comment]
I can modify prepared settings depends on input sources.
Could you tell me your input source? (French?)

**Comment by steph643** [comment]
Sorry for the late reply. My input source is ***French - PC***.

I found other issues:
* "Use PC Style Alt+F4" does a "select all" instead of quiting the application
* "Command+Y sends Command+Shift+Z (Windows-style redo)" does not work

**Comment by tekezo** [comment]
Thank you for information.

I've merged these settings into prepared settings as follows.
https://github.com/tekezo/Karabiner/commit/7ea1236f1a044bd13756cfc40c2eaa20608c3019

These prepared settings work with French input sources since Karabiner 10.5.9.
Please use the latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by steph643** [comment]
Thanks a lot, @tekezo!

* "Use PC Style Undo" and "Use PC Style Select All" now work like a charm.
* "Use PC Style Alt+F4" works very well, except with Terminal.
* "Command+Y sends Command+Shift+Z (Windows-style redo)" still does not work.

Thanks again!

**Comment by tekezo** [comment]
Thank you for confirmation.

I've improved Alt+F4 at Karabiner 10.5.10. (the latest beta version)

And the third setting changes **Command**+Y.
If you want to change control+Y, please use "PC Style Redo" that has been added at v10.5.10.

**Comment by steph643** [comment]
Thank you very much!
* Alt+F4 now works in Terminal
* "PC Style Redo" works as expected

**Comment by tekezo** [comment]
Thank you!
